AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 deployment

Resources:

  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.xlarge
      ImageId: ami-009be0edec0817ffd   
      SecurityGroupIds:
        - !Ref InstanceSG
